In [ ]:
import whisper
from transformers import WhisperForConditionalGeneration

model1 = WhisperForConditionalGeneration.from_pretrained("openai/whisper-small").to("cuda")
model2=whisper.load_model("small")

print(model1)
print(model2)

In [29]:
print(model1)

WhisperForConditionalGeneration(
  (model): WhisperModel(
    (encoder): WhisperEncoder(
      (conv1): Conv1d(80, 768, kernel_size=(3,), stride=(1,), padding=(1,))
      (conv2): Conv1d(768, 768, kernel_size=(3,), stride=(2,), padding=(1,))
      (embed_positions): Embedding(1500, 768)
      (layers): ModuleList(
        (0-11): 12 x WhisperEncoderLayer(
          (self_attn): WhisperAttention(
            (k_proj): Linear(in_features=768, out_features=768, bias=False)
            (v_proj): Linear(in_features=768, out_features=768, bias=True)
            (q_proj): Linear(in_features=768, out_features=768, bias=True)
            (out_proj): Linear(in_features=768, out_features=768, bias=True)
          )
          (self_attn_layer_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
          (activation_fn): GELUActivation()
          (fc1): Linear(in_features=768, out_features=3072, bias=True)
          (fc2): Linear(in_features=3072, out_features=768, bias=True)
          (f

In [30]:
print(model2)

Whisper(
  (encoder): AudioEncoder(
    (conv1): Conv1d(80, 768, kernel_size=(3,), stride=(1,), padding=(1,))
    (conv2): Conv1d(768, 768, kernel_size=(3,), stride=(2,), padding=(1,))
    (blocks): ModuleList(
      (0-11): 12 x ResidualAttentionBlock(
        (attn): MultiHeadAttention(
          (query): Linear(in_features=768, out_features=768, bias=True)
          (key): Linear(in_features=768, out_features=768, bias=False)
          (value): Linear(in_features=768, out_features=768, bias=True)
          (out): Linear(in_features=768, out_features=768, bias=True)
        )
        (attn_ln): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
        (mlp_ln): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      )
    )
    (ln_post): LayerNorm((768,), eps=1e-0

In [25]:
print(model1.parameters())



<generator object Module.parameters at 0x000001C380ABFBC0>


In [26]:
print(model2.parameters())

<generator object Module.parameters at 0x000001C380ABF920>


In [34]:
for i in model2.parameters():
    print(i)
    break

Parameter containing:
tensor([[[-6.4545e-03, -6.4545e-03, -1.4877e-02],
         [ 2.8275e-02,  2.9892e-02,  1.0704e-02],
         [ 1.9293e-03, -3.9795e-02, -6.6528e-02],
         ...,
         [-3.1033e-03, -9.7122e-03, -3.2463e-03],
         [-1.6451e-03, -1.1742e-02, -2.6531e-03],
         [-1.2085e-02, -3.1403e-02, -1.8692e-02]],

        [[-7.7286e-03, -7.0801e-03, -1.3550e-02],
         [ 1.1520e-02,  1.1215e-02,  1.0849e-02],
         [-1.5182e-02, -1.9730e-02, -1.2169e-02],
         ...,
         [ 8.5068e-04, -4.4708e-03, -3.3913e-03],
         [ 1.1425e-03, -4.7722e-03, -2.8610e-03],
         [-8.8978e-04, -9.6664e-03, -7.0610e-03]],

        [[-4.4632e-03, -5.4741e-03,  2.8992e-03],
         [-8.3771e-03, -9.0103e-03, -3.7041e-03],
         [ 1.8738e-02,  3.0914e-02,  3.7140e-02],
         ...,
         [-2.5131e-02,  3.0762e-02, -3.3447e-02],
         [-2.6749e-02,  2.4811e-02, -3.2776e-02],
         [-4.0497e-02,  3.1616e-02, -5.5725e-02]],

        ...,

        [[-1.462

In [73]:
p1=model1.parameters()
p2=model2.parameters()

p1=list(p1)
p2=list(p2)

print(len(p1))
print(len(p2))


479
478


In [85]:
for i,j in zip(p1[::-1],p2[::-1]):
    print(i.shape,j.shape)

torch.Size([768]) torch.Size([768])
torch.Size([768]) torch.Size([768])
torch.Size([768]) torch.Size([768])
torch.Size([768]) torch.Size([768])
torch.Size([768]) torch.Size([768])
torch.Size([768, 3072]) torch.Size([768, 3072])
torch.Size([3072]) torch.Size([3072])
torch.Size([3072, 768]) torch.Size([3072, 768])
torch.Size([768]) torch.Size([768])
torch.Size([768]) torch.Size([768])
torch.Size([768]) torch.Size([768])
torch.Size([768, 768]) torch.Size([768, 768])
torch.Size([768]) torch.Size([768])
torch.Size([768, 768]) torch.Size([768, 768])
torch.Size([768]) torch.Size([768, 768])
torch.Size([768, 768]) torch.Size([768])
torch.Size([768, 768]) torch.Size([768, 768])
torch.Size([768]) torch.Size([768])
torch.Size([768]) torch.Size([768])
torch.Size([768]) torch.Size([768])
torch.Size([768, 768]) torch.Size([768, 768])
torch.Size([768]) torch.Size([768])
torch.Size([768, 768]) torch.Size([768, 768])
torch.Size([768]) torch.Size([768, 768])
torch.Size([768, 768]) torch.Size([768])
torc

In [97]:
for i in range(-1,-len(p1),-1):
    print(i)
    if((p1[i]-p2[i]).sum()!=0):
        print(p1[i]-p2[i])
        break

-1
-2
-3
-4
-5
-6
-7
-8
-9
-10
-11
-12
-13
tensor([-5.2177e-02, -6.9855e-01,  1.7758e-01, -1.3082e-01,  3.6549e-01,
         4.7774e-01,  7.0648e-02,  1.0849e-01,  1.5796e-01,  1.8457e-01,
        -7.0587e-02,  7.9803e-02, -2.6761e-01,  2.5931e-01,  1.9217e-01,
         1.8898e-01,  1.7426e-01, -3.3911e-01,  1.2841e+00,  5.4953e-01,
         3.0524e-01,  2.0978e-01,  8.5953e-02, -1.0439e-01, -1.4999e-02,
        -7.4619e-01, -1.9568e-01, -2.3608e-01, -1.1520e-01, -3.2347e-01,
        -1.4545e-01,  3.9697e-01,  4.3474e-01, -4.3004e-01,  5.0190e-01,
         5.7964e-02,  2.5565e-01, -3.2632e-01, -1.4642e+00, -3.9830e-01,
         1.8735e-01,  8.9439e-02,  4.3879e-02,  1.4465e-02,  8.7531e-01,
         2.3041e-03, -1.4583e-01, -8.8674e-01, -1.3414e-01, -3.9186e-01,
        -6.3588e-01,  2.5578e-01,  3.2036e-01, -1.0587e-01, -2.4416e-01,
        -2.4109e-01, -2.2479e-01, -1.2955e-01, -1.5819e-01,  4.5978e-01,
        -5.0156e-02,  2.0737e-01, -7.2632e-03,  4.3707e-03, -4.2580e-01,
        

In [99]:
print(p1[-13]-p2[-13])

tensor([-5.2177e-02, -6.9855e-01,  1.7758e-01, -1.3082e-01,  3.6549e-01,
         4.7774e-01,  7.0648e-02,  1.0849e-01,  1.5796e-01,  1.8457e-01,
        -7.0587e-02,  7.9803e-02, -2.6761e-01,  2.5931e-01,  1.9217e-01,
         1.8898e-01,  1.7426e-01, -3.3911e-01,  1.2841e+00,  5.4953e-01,
         3.0524e-01,  2.0978e-01,  8.5953e-02, -1.0439e-01, -1.4999e-02,
        -7.4619e-01, -1.9568e-01, -2.3608e-01, -1.1520e-01, -3.2347e-01,
        -1.4545e-01,  3.9697e-01,  4.3474e-01, -4.3004e-01,  5.0190e-01,
         5.7964e-02,  2.5565e-01, -3.2632e-01, -1.4642e+00, -3.9830e-01,
         1.8735e-01,  8.9439e-02,  4.3879e-02,  1.4465e-02,  8.7531e-01,
         2.3041e-03, -1.4583e-01, -8.8674e-01, -1.3414e-01, -3.9186e-01,
        -6.3588e-01,  2.5578e-01,  3.2036e-01, -1.0587e-01, -2.4416e-01,
        -2.4109e-01, -2.2479e-01, -1.2955e-01, -1.5819e-01,  4.5978e-01,
        -5.0156e-02,  2.0737e-01, -7.2632e-03,  4.3707e-03, -4.2580e-01,
         4.8157e-02, -1.5050e+00, -5.3029e-01,  3.5